export const CONSTANTS = Object.freeze({
  GAME_SETTINGS: {
    FULL_STOP: 1,
    GRAVITY: 1,
    IDLE_COUNTER: 500,
    DEBUG: false
  },
  GAME_STATES: {
    SELECTING: "selecting",
    PLAYING: "playing",
    PAUSED: "paused",
    OVER: "over",
  },
  GAME_TYPES: {
    FEED: "feed",
    PLAY: "play",
    PAT: "pat",
  },
  AIRBORNE_STATES: {
    JUMPING: "jumping",
    DOUBLE_JUMPING: "double_jumping",
    FALLING: "falling",
    SLAMMING: "slamming",
    GROUNDED: "grounded"
  },
  ANIMAL_STATES: {
    CROUCHING: "crouching",
    RESTING: "resting",
    EATING: "eating",
    MOVING: "moving",
    IDLE: "idle",
    PLAYING: "playing",
    HIDING: "hiding",
    CLIMBING: "climbing",
  },
  COLLISION: {
    TOP: "collision_top",
    BOTTOM: "collision_bottom",
    LEFT: "collision_left",
    RIGHT: "collision_right",
    FRONT: "collision_front",
    BACK: "collision_back",
    CORNER_TOP_RIGHT: "collision_corner_top_right",
    CORNER_BOTTOM_RIGHT: "collision_corner_bottom_right",
    CORNER_TOP_LEFT: "collision_corner_top_left",
    CORNER_BOTTOM_LEFT: "collision_corner_bottom_left",
    NONE: "collision_none",
  },
  DIRECTION: {
    UP: "direction_up",
    DOWN: "direction_down",
    LEFT: "direction_left",
    RIGHT: "direction_right",
    NONE: "direction_none",
  },
  ANIMAL_TYPES: {
    NIT: {
      maxVelocity: 10,
      acceleration: 0.4,
      type: "cat",
      size: 50,
      jumpingPower: 18,
      name: "Nit",
      color: "gray",
    },
    DIA: {
      maxVelocity: 15,
      acceleration: 0.5,
      type: "cat",
      size: 25,
      jumpingPower: 22,
      name: "Dia",
      color: "white",
    },
  },
  SCREEN: {
    PADDING_LEFT: 5,
    PADDING_RIGHT: 5,
    PADDING_TOP: 5,
    PADDING_BOTTOM: 20,
    BACKGROUND_COLOR: "black",
    OUTSIDE_COLOR: "green",
    ASPECT_RATIO: 16 / 9,
    MIN_HEIGHT: 360,
    MIN_WIDTH: 480,
    FRAMERATE: 1000 / 24,
    WIDTH: 1920,
    HEIGHT: 1080,
  },
});
