import { Animal } from "./Animal.js";
export const CONSTANTS = Object.freeze({
  GAME_SETTINGS: {
    FULL_STOP: 2,
    GRAVITY: 0.8,
    IDLE_COUNTER: 500,
    DEBUG: true,
    DASH_THRESHHOLD_MS: 80,
    FRAMERATE: 1000 / 60,
  },
  GAME_STATES: {
    SELECTING: "selecting",
    PLAYING: "playing",
    PAUSED: "paused",
    OVER: "over",
  },
  GAME_TYPES: {
    FEED: "feed",
    PLAY: "play",
    PAT: "pat",
  },
  CHARACTER_STATES: {
    //IDLE STATES
    IDLE: "idle",
    SLEEPING: "sleeping",
    RESTING: "resting",
    SLEEPING: "sleeping",
    EATING: "eating",
    PLAYING: "playing",
    HIDING: "hiding",
    //MOVEMENT STATES
    SLAMMING: "slamming",
    GROUNDED: "grounded",
    DROPPING: "dropping",
    GRIPPING: "gripping",
    CROUCHING: "crouching",
    IMPULSING: "impulsing",
    STANDING: "standing",
    MOVING_LEFT: "moving_left",
    MOVING_RIGHT: "moving_right",
    WAITING_KEYPRESS_LEFT: "waiting_keypress_left",
    WAITING_KEYPRESS_RIGHT: "waiting_keypress_right",
    DASHING_LEFT: "dashing_left",
    DASHING_RIGHT: "dashing_right",
    //MODEL STATES
    CROUCHED: "crouched",
    JUMPING: "jumping",
    DOUBLE_JUMPING: "double_jumping",
    FALLING: "falling",
    CLIMBING: "climbing",
  },
  COLLISION: {
    TOP: "collision_top",
    BOTTOM: "collision_bottom",
    LEFT: "collision_left",
    RIGHT: "collision_right",
    FRONT: "collision_front",
    BACK: "collision_back",
    CORNER_TOP_RIGHT: "collision_corner_top_right",
    CORNER_BOTTOM_RIGHT: "collision_corner_bottom_right",
    CORNER_TOP_LEFT: "collision_corner_top_left",
    CORNER_BOTTOM_LEFT: "collision_corner_bottom_left",
    NONE: "collision_none",
  },
  DIRECTION: {
    UP: "direction_up",
    DOWN: "direction_down",
    LEFT: "direction_left",
    RIGHT: "direction_right",
    NONE: "direction_none",
  },
  SCREEN_SETTINGS: {
    PADDING_LEFT: 5,
    PADDING_RIGHT: 5,
    PADDING_TOP: 5,
    PADDING_BOTTOM: 20,
    BACKGROUND_COLOR: "black",
    OUTSIDE_COLOR: "green",
    ASPECT_RATIO: 16 / 9,
    MIN_HEIGHT: 360,
    MIN_WIDTH: 480,
    WIDTH: 1920,
    HEIGHT: 1080,
  },
  ANIMAL_TYPES:{
    CAT:"cat",
    DOG:"dog",
    SHEEP:"sheep",
    BEAR: "bear",
    RACOON: "racoon",
    RABBIT: "rabbit",
    KANGAROO: "kangaroo",
    SNAKE: "snake",
  }
});
export const ANIMALS = Object.freeze({
  NIT: new Animal("Nit", CONSTANTS.ANIMAL_TYPES.CAT, "gray", 8, 0.4, 50, 14, 20),
  DIA: new Animal("Dia", CONSTANTS.ANIMAL_TYPES.CAT, "white", 12, 0.6, 25, 22, 30),
});